export enum Category {
  RESTAURANTS = "RESTAURANTS",
  TRAVEL = "TRAVEL",
  ENTERTAINMENT = "ENTERTAINMENT",
  FASHION = "FASHION",
  ELECTRONICS = "ELECTRONICS",
}

export enum UserTypes {
  ADMINISTRATOR = "ADMINISTRATOR",
  COMPANY = "COMPANY",
  CUSTOMER = "CUSTOMER",
}
